### ISSUE TITLE
Ceph support

### ISSUE THREAD

**Issue by CvH** [DerDanilo/proxmox-stuff#12]
I am currently starting to fiddling around to create some proper proxmox backup solution for our servers.
We are using ceph as storage, that is not yet supported at this script.

I have no idea yet if I can use this script (if so I pr the changes), if not I wanted to to archive at least what is needed to get ceph support. Might be helpful for someone.

We are currently doing a hacky approach that works, for us, too. The excludes are important, the OSDs are typical including TB of data.
```
tar -cPvf "/path/backup.tar" \
  --exclude='/var/lib/ceph/osd/ceph*/*' \
  --exclude='/var/lib/ceph/tmp' \
  /etc/ \
  /root/ \
  /var/lib/ceph/ \
  /var/lib/corosync/ \
  /var/lib/pve-cluster/
```

For restore these files are important, otherwise your OSDs won't work.
```
/etc/ceph/
/etc/systemd/system/ceph-mgr.target.wants/ceph-mgr@*.service
/etc/systemd/system/ceph-mon.target.wants/ceph-mon@*.service
```

**Comment by DerDanilo** [comment]
This is a good idea! I suggest we allow to enable Ceph config backup with a boolean switch. This way the script won't fail if ceph is not being used.
There are not many files that are to be backed up from Ceph. It should also **not** include the MON data. This backup script's idea is purely for config files and should stay this way, at least that is what I think (for now).

I'd rather suggest to define important Ceph files directly. The `ceph.conf` doesn't also contain all currently active config parameter since CLI overwrites could have happened. So it's advisable to export the current config maybe to `/tmp` and take it from there.

Suggestion in general:
We are using croit.io mostly for Ceph clusters since it's way easier to manage and has a config backup build in. It has a free option if RBD is enough. But even the minimum license pricing is affordable since it safes ton's of hours maintaining a Ceph cluster. Please contact me directly if you are interested. 
The PVE ceph integration is fine but I don't like to use it since it lacks a lot of features and mgmt options.

**Comment by DerDanilo** [comment]
@CvH Please open a PR so we can get this integrated. I'd like to have the ceph part purely option. There could be a command line switch to include ceph releated config for example.

**Comment by CvH** [comment]
It works at production servers so I can not test here anything easily.

I have a script that works but has no switches included - a bit ugly but works.
I can post my current approach if this helps.

**Comment by DerDanilo** [comment]
That might help. Please create PR and try to integrate your code. It may take some time but we'll get that integrated if it works

**Comment by DerDanilo** [comment]
@CvH Are you still up for a PR? I might find some time soon to check on that, even though I am not using (and would not recommend) Ceph managed by PVE.

**Comment by DerDanilo** [comment]
@CvH Are you still interessted to share your code? Otherwise I'll close this issue.
